--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENDA
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."AGENDA" 
   (	"APELLIDO" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DOMICILIO" VARCHAR2(30 BYTE), 
	"TELEFONO" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.AGENDA
SET DEFINE OFF;
Insert into CURSO_ORACLE.AGENDA (APELLIDO,NOMBRE,DOMICILIO,TELEFONO) values ('Alvarez','Alberto','Colon 123','4234567');
Insert into CURSO_ORACLE.AGENDA (APELLIDO,NOMBRE,DOMICILIO,TELEFONO) values ('Juarez','Juan','Avellaneda 135','4458787');
Insert into CURSO_ORACLE.AGENDA (APELLIDO,NOMBRE,DOMICILIO,TELEFONO) values ('Lopez','Maria','Urquiza 333','4545454');
Insert into CURSO_ORACLE.AGENDA (APELLIDO,NOMBRE,DOMICILIO,TELEFONO) values ('Lopez','Jose','Urquiza 333','4545454');
Insert into CURSO_ORACLE.AGENDA (APELLIDO,NOMBRE,DOMICILIO,TELEFONO) values ('Salas','Susana','Gral. Paz 1234','4123456');
