--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALUMNOS
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."ALUMNOS" 
   (	"LEGAJO" CHAR(5 BYTE), 
	"DOCUMENTO" CHAR(8 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"CURSO" CHAR(1 BYTE), 
	"MATERIA" VARCHAR2(30 BYTE), 
	"NOTAFINAL" NUMBER(4,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.ALUMNOS
SET DEFINE OFF;
Insert into CURSO_ORACLE.ALUMNOS (LEGAJO,DOCUMENTO,NOMBRE,CURSO,MATERIA,NOTAFINAL) values ('A123 ','22222222','Perez Patricia','5','Matematica','9');
Insert into CURSO_ORACLE.ALUMNOS (LEGAJO,DOCUMENTO,NOMBRE,CURSO,MATERIA,NOTAFINAL) values ('A234 ','23333333','Lopez Ana','5','Matematica','9');
Insert into CURSO_ORACLE.ALUMNOS (LEGAJO,DOCUMENTO,NOMBRE,CURSO,MATERIA,NOTAFINAL) values ('A345 ','24444444','Garcia Carlos','6','Matematica','8,5');
Insert into CURSO_ORACLE.ALUMNOS (LEGAJO,DOCUMENTO,NOMBRE,CURSO,MATERIA,NOTAFINAL) values ('A348 ','25555555','Perez Patricia','6','Lengua','7,85');
Insert into CURSO_ORACLE.ALUMNOS (LEGAJO,DOCUMENTO,NOMBRE,CURSO,MATERIA,NOTAFINAL) values ('A457 ','26666666','Perez Fabian','6','Lengua','3,2');
--------------------------------------------------------
--  DDL for Index I_ALUMNOS_NOMBRE
--------------------------------------------------------

  CREATE INDEX "CURSO_ORACLE"."I_ALUMNOS_NOMBRE" ON "CURSO_ORACLE"."ALUMNOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index I_ALUMNOS_LEGAJO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."I_ALUMNOS_LEGAJO" ON "CURSO_ORACLE"."ALUMNOS" ("LEGAJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ALUMNOS
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."ALUMNOS" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "CURSO_ORACLE"."ALUMNOS" MODIFY ("LEGAJO" NOT NULL ENABLE);
