--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."CLIENTES" 
   (	"CODIGO" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DOMICILIO" VARCHAR2(30 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"CODIGOPROVINCIA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.CLIENTES
SET DEFINE OFF;
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('101','Lopez Marcos','Colon 111','Córdoba','1');
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('102','Perez Ana','San Martin 222','Cruz del Eje','1');
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('103','Garcia Juan','Rivadavia 333','Villa Maria','1');
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('104','Perez Luis','Sarmiento 444','Rosario','2');
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('105','Gomez Ines','San Martin 666','Santa Fe','2');
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('106','Torres Fabiola','Alem 777','La Plata','4');
Insert into CURSO_ORACLE.CLIENTES (CODIGO,NOMBRE,DOMICILIO,CIUDAD,CODIGOPROVINCIA) values ('107','Garcia Luis','Sucre 475','Santa Rosa','5');
--------------------------------------------------------
--  DDL for Index SYS_C007047
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007047" ON "CURSO_ORACLE"."CLIENTES" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."CLIENTES" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
