--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPORTES
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."DEPORTES" 
   (	"CODIGO" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PROFESOR" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.DEPORTES
SET DEFINE OFF;
Insert into CURSO_ORACLE.DEPORTES (CODIGO,NOMBRE,PROFESOR) values ('1','tenis','Marcelo Roca');
Insert into CURSO_ORACLE.DEPORTES (CODIGO,NOMBRE,PROFESOR) values ('2','natacion','Marta Torres');
Insert into CURSO_ORACLE.DEPORTES (CODIGO,NOMBRE,PROFESOR) values ('3','basquet','Luis Garcia');
Insert into CURSO_ORACLE.DEPORTES (CODIGO,NOMBRE,PROFESOR) values ('4','futbol','Marcelo Roca');
--------------------------------------------------------
--  DDL for Index PK_DEPORTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."PK_DEPORTES" ON "CURSO_ORACLE"."DEPORTES" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPORTES
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."DEPORTES" ADD CONSTRAINT "PK_DEPORTES" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
