--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."EMPLEADOS" 
   (	"NOMBRE" VARCHAR2(30 BYTE), 
	"DOCUMENTO" CHAR(8 BYTE), 
	"DOMICILIO" VARCHAR2(30 BYTE), 
	"SECCION" VARCHAR2(20 BYTE), 
	"SUELDO" NUMBER(6,2), 
	"CANTIDADHIJOS" NUMBER(2,0), 
	"FECHAINGRESO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.EMPLEADOS
SET DEFINE OFF;
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Juan Perez','22333444','Colon 123','Gerencia','5000','2',to_date('10/10/1980 00:00:00','DD/MM/RRRR HH24:MI:SS'));
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Ana Acosta','23444555','Caseros 987','Secretaria','2000','0',to_date('15/08/1998 00:00:00','DD/MM/RRRR HH24:MI:SS'));
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Lucas Duarte','25666777','Sucre 235','Sistemas','4000','1',null);
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Pamela Gonzalez','26777888','Sarmiento 873','Secretaria','2200','3',null);
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Marcos Juarez','30000111','Rivadavia 801','Contaduria','3000','0',to_date('26/08/2000 00:00:00','DD/MM/RRRR HH24:MI:SS'));
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Yolanda Perez','35111222','Colon 180','Administracion','3200','1',to_date('25/09/2001 00:00:00','DD/MM/RRRR HH24:MI:SS'));
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Rodolfo Perez','35555888','Coronel Olmedo 588','Sistemas','4000','3',null);
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Martina Rodriguez','30141414','Sarmiento 1234','Administracion','3800','4',to_date('14/12/2000 00:00:00','DD/MM/RRRR HH24:MI:SS'));
Insert into CURSO_ORACLE.EMPLEADOS (NOMBRE,DOCUMENTO,DOMICILIO,SECCION,SUELDO,CANTIDADHIJOS,FECHAINGRESO) values ('Andres Costa','28444555',null,'Secretaria',null,null,to_date('08/08/1990 00:00:00','DD/MM/RRRR HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index SYS_C007025
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007025" ON "CURSO_ORACLE"."EMPLEADOS" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."EMPLEADOS" ADD PRIMARY KEY ("DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
