--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FERRETERIA
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."FERRETERIA" 
   (	"ID_FERRETERIA" NUMBER(*,0), 
	"ARTICULO" VARCHAR2(50 BYTE), 
	"COD_FABRICANTE" NUMBER(10,0), 
	"PESO" NUMBER(4,0), 
	"CATEGORIA" VARCHAR2(50 BYTE), 
	"PRECIO_VENTA" NUMBER(6,2), 
	"PRECIO_COSTO" NUMBER(6,2), 
	"EXISTENCIAS" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.FERRETERIA
SET DEFINE OFF;
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('2','TALADRO WALT','1012546955','45','CONSTRUCCION','400','560','20');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('3','ALICATE ACE','1012432365','23','MECANICA','200','350,25','120');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('4','PALA SENIC','1012345678','16','CONSTRUCCION','100','230,5','200');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('5','TALADRO MILLWAKEE','1012545210','55','CONSTRUCCION','300','423,5','50');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('6','GRIFO APERTURA MANOS','1010023654','26','PLOMERIA','400','560,25','90');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('7','FREGADERO MURAL','1015487966','200','PLOMERIA','600','780,5','52');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('8','TALADRO ELECTRICO BOSCH','1025493013','34','CONSTRUCCION','250','380,25','41');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('9','CEPILLO CONICO ONDULADO','1025852000','44','EBANISTERIA','150','240,25','88');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('10','CEPILLO TAZA ONDULADO','122247789','49','EBANISTERIA','148','240,5','90');
Insert into CURSO_ORACLE.FERRETERIA (ID_FERRETERIA,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,PRECIO_VENTA,PRECIO_COSTO,EXISTENCIAS) values ('11','CEPILLO TAZA TRENZADA','1016467985','42','EBANISTERIA','139','210,5','89');
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007015" ON "CURSO_ORACLE"."FERRETERIA" ("ID_FERRETERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FERRETERIA
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."FERRETERIA" ADD PRIMARY KEY ("ID_FERRETERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CURSO_ORACLE"."FERRETERIA" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "CURSO_ORACLE"."FERRETERIA" MODIFY ("COD_FABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "CURSO_ORACLE"."FERRETERIA" MODIFY ("ARTICULO" NOT NULL ENABLE);
  ALTER TABLE "CURSO_ORACLE"."FERRETERIA" MODIFY ("ID_FERRETERIA" NOT NULL ENABLE);
