--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INSCRIPTOS
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."INSCRIPTOS" 
   (	"DOCUMENTO" CHAR(8 BYTE), 
	"CODIGODEPORTE" NUMBER(2,0), 
	"MATRICULA" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.INSCRIPTOS
SET DEFINE OFF;
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0001','3','s');
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0002','3','s');
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0003','3','n');
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0004','2','s');
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0005','2','s');
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0006','4','n');
Insert into CURSO_ORACLE.INSCRIPTOS (DOCUMENTO,CODIGODEPORTE,MATRICULA) values ('ins-0007','5','n');
--------------------------------------------------------
--  DDL for Index PK_INSCRIPTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."PK_INSCRIPTOS" ON "CURSO_ORACLE"."INSCRIPTOS" ("DOCUMENTO", "CODIGODEPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table INSCRIPTOS
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."INSCRIPTOS" ADD CONSTRAINT "PK_INSCRIPTOS" PRIMARY KEY ("DOCUMENTO", "CODIGODEPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
