--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEDICAMENTOS
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."MEDICAMENTOS" 
   (	"CODIGO" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"LABORATORIO" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER(6,2), 
	"CANTIDAD" NUMBER(3,0), 
	"FECHAVENCIMIENTO" DATE, 
	"NUMEROLOTE" NUMBER(6,0) DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.MEDICAMENTOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007024
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007024" ON "CURSO_ORACLE"."MEDICAMENTOS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEDICAMENTOS
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."MEDICAMENTOS" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CURSO_ORACLE"."MEDICAMENTOS" MODIFY ("FECHAVENCIMIENTO" NOT NULL ENABLE);
