--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PELICULAS
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."PELICULAS" 
   (	"CODIGO" NUMBER(4,0), 
	"TITULO" VARCHAR2(40 BYTE), 
	"ACTOR" VARCHAR2(20 BYTE), 
	"DURACION" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.PELICULAS
SET DEFINE OFF;
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1020','Mision imposible','Tom Cruise','120');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1021','Harry Potter y la piedra filosofal','Daniel R.','180');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1022','Harry Potter y la camara secreta','Daniel R.','190');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1200','Mision imposible 2','Tom Cruise','120');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1234','Mujer bonita','Richard Gere','120');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('900','Tootsie','D. Hoffman','90');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1300','Un oso rojo','Julio Chavez','100');
Insert into CURSO_ORACLE.PELICULAS (CODIGO,TITULO,ACTOR,DURACION) values ('1301','Elsa y Fred','China Zorrilla','110');
--------------------------------------------------------
--  DDL for Index SYS_C007017
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007017" ON "CURSO_ORACLE"."PELICULAS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PELICULAS
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."PELICULAS" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CURSO_ORACLE"."PELICULAS" MODIFY ("TITULO" NOT NULL ENABLE);
