--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRUEBATABLA
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."PRUEBATABLA" 
   (	"IDPRUEBA" NUMBER(*,0), 
	"PRUEBA" VARCHAR2(20 BYTE), 
	"NUMERO" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.PRUEBATABLA
SET DEFINE OFF;
Insert into CURSO_ORACLE.PRUEBATABLA (IDPRUEBA,PRUEBA,NUMERO) values ('1','Prueba en 1','26,34');
Insert into CURSO_ORACLE.PRUEBATABLA (IDPRUEBA,PRUEBA,NUMERO) values ('2','Prueba en 2','36,75');
--------------------------------------------------------
--  DDL for Index SYS_C007029
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007029" ON "CURSO_ORACLE"."PRUEBATABLA" ("IDPRUEBA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRUEBATABLA
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."PRUEBATABLA" ADD PRIMARY KEY ("IDPRUEBA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CURSO_ORACLE"."PRUEBATABLA" MODIFY ("PRUEBA" NOT NULL ENABLE);
  ALTER TABLE "CURSO_ORACLE"."PRUEBATABLA" MODIFY ("IDPRUEBA" NOT NULL ENABLE);
