--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UPERSONA
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."UPERSONA" 
   (	"IDUPERSONA" NUMBER(*,0), 
	"NOMBREUPERSONA" VARCHAR2(50 BYTE), 
	"CLAVEUPERSONA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.UPERSONA
SET DEFINE OFF;
Insert into CURSO_ORACLE.UPERSONA (IDUPERSONA,NOMBREUPERSONA,CLAVEUPERSONA) values ('1','usuario1','clave1');
--------------------------------------------------------
--  DDL for Index SYS_C007037
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007037" ON "CURSO_ORACLE"."UPERSONA" ("IDUPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table UPERSONA
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."UPERSONA" ADD PRIMARY KEY ("IDUPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CURSO_ORACLE"."UPERSONA" MODIFY ("IDUPERSONA" NOT NULL ENABLE);
