--------------------------------------------------------
-- Archivo creado  - sábado-abril-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "CURSO_ORACLE"."USUARIOS" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"CLAVE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CURSO_ORACLE.USUARIOS
SET DEFINE OFF;
Insert into CURSO_ORACLE.USUARIOS (NOMBRE,CLAVE) values ('Jose','4336');
Insert into CURSO_ORACLE.USUARIOS (NOMBRE,CLAVE) values ('Juan','98878');
Insert into CURSO_ORACLE.USUARIOS (NOMBRE,CLAVE) values ('Josefina','4339yhg6');
Insert into CURSO_ORACLE.USUARIOS (NOMBRE,CLAVE) values ('Juaquin','9887sdnc');
--------------------------------------------------------
--  DDL for Index SYS_C007006
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURSO_ORACLE"."SYS_C007006" ON "CURSO_ORACLE"."USUARIOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "CURSO_ORACLE"."USUARIOS" ADD PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CURSO_ORACLE"."USUARIOS" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CURSO_ORACLE"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
